### ISSUE TITLE
Rationale - Just Your Type - Week 9

### ISSUE THREAD

**Issue by char1129** [char1129/just-your-type#1]
**1. Explain your chosen concept.**
I chose a Dr Seuss quote. Since he is known for his quirky fun books, I wanted the title to mimic the play in his books by bouncing his name to and fro, ending up at different positions on the page.
**2. Why did you choose these typefaces?**
I chose two script san-serif fonts that mimics the fun, messy, carefree nature of Dr. Seuss' characters.
**3. Why did you choose this type scale?**
I chose the Golden Ratio scale because a larger x-height (than the standard generated ratio) that would be easier to read given the choice of font.
**4. Why did you choose these colours?**
I chose a variety of colours that the author's name and enlarged hanging punctuation cycle through as the viewport size increases from red, green, blue, purple, and orange to mimic the vibrant colours of Dr. Seuss books.
**5. How did you effectively use grids and modular css?**
I effectively used grids to show and hide different locations of text so that it gives an appearance of moving, jumping text. Modular css was used to create an icon in the centre of the screen that allows the user to click on it to be directed to one of Dr. Seuss' animations on Youtube.
**6. What challenges did you overcome?**
I overcame the challenge of the Golden Ratio Typografier having errors of missing and negative values in the CSS. Additionally, after the initial errors were fixed and verified by Markbot, the text continued not to scale. I used tags within the html (such as tera) and targeted specific tag's font-sizes in the css to overcome this challenge.
Another challenge I overcame with help from @muxlowc was the Seuss, in Dr. Seuss h2 tag was bleeding off the page. This was remedied by adding padding to the tag.

@muxlowc @char1129 

Attached layout sheet shown to you on Wednesday, Feb 12th.
![layouts](https://user-images.githubusercontent.com/55107755/74391201-869a8a80-4dd1-11ea-9e2e-36f36b641302.jpg)

**Comment by char1129** [comment]
@muxlowc Let me know if you'd like me to close this as well 😊 Stay healthy!

**Comment by muxlowc** [comment]
@char1129 yes, please close this issue! thanks!
